# Generated by Django 4.0.1 on 2022-01-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('company_website', models.URLField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('jobpost_url', models.URLField()),
                ('applied', models.BooleanField(default=False)),
                ('office_location', models.CharField(max_length=200)),
                ('job_location', models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('I', 'In Office')], max_length=1)),
                ('app_status', models.CharField(choices=[('SA', 'Submitted Application'), ('SI', 'Scheduled Interview'), ('RO', 'Received Offer'), ('NS', 'Negotiation State'), ('NO', 'No Offer'), ('RC', 'Reference Check')], max_length=2)),
            ],
        ),
    ]
