# Generated by Django 4.0.1 on 2022-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=75)),
                ('company_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('status', models.CharField(choices=[('LR', 'Sent LinkedIn Request'), ('LM', 'Sent LinkedIn Message'), ('GI', 'Got an intro'), ('SI', 'Scheduled Interview')], max_length=2)),
            ],
        ),
    ]
